// vue-ui/src/Dashboard.vue
<template>
    <Template>
        <div class="pt-3 mt-5">
            <p class="jumbotron lead text-primary"><strong>This is dashboard.</strong></p>
        </div>
    </Template>
</template>

<script>
    import Template from './Template';

    export default {
        name: "Dashboard",
        components: {Template}
    }
</script>

<style scoped>

</style>

// rbac-react/src/Dashboard.js
import React, {Component} from "react";

class Dashboard extends Component{
    render() {
        return (
            <div className="pt-3 mt-5">
                <p className="lead jumbotron">
                    <var>This is dashboard.</var>
                </p>
            </div>
        );
    }
}

export default Dashboard;
